# Generated by Django 3.2.25 on 2025-04-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='benefits',
            field=models.TextField(default='No benefits listed', help_text='Comma separated list of membership benefits'),
        ),
    ]
