# Generated by Django 3.2.25 on 2025-04-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseplan',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
